name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*
    - soodpr-patch-1
  pull_request:
    branches:
      - master
jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v3      
        name: Build & push Docker image
        with:
          image: prisood/oneview-python-image
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
